# Generated by Django 3.2.9 on 2022-03-28 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0009_alter_todo_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='isCompleted',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='update_at',
        ),
    ]
