# Generated by Django 3.2.9 on 2022-04-01 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0011_todo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='images/'),
        ),
    ]
